
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sendmail", targetNamespace = "http://example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sendmail {


    /**
     * 
     * @param url
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sendEmailReturn", targetNamespace = "http://example", partName = "sendEmailReturn")
    public String sendEmail(
        @WebParam(name = "url", targetNamespace = "http://example", partName = "url")
        String url);

}
